services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - chatbot-network
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - chatbot-network
    environment:
      # Use Docker service name 'backend' to reach backend container
      - BACKEND_URL=http://backend:8000

networks:
  chatbot-network:
    driver: bridge
